Repository 1024pix/pix-360, pull requests merged in 2023-02, with the labels that each got.

#114 Changer le format de logs et le mettre en JSON
  config/application.rb
Labels: tech-review-needed, team-captains

#115 [TECH] Met à jour rails en version 7.0.4.2
  Gemfile.lock
Labels: tech-review-needed, team-captains

#117 [TECH] Ajouter la config pour renovate
  .github/renovate.json
Labels: tech-review-needed

#119 [BUGFIX] Les traces ne sont pas au format JSON en production
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/production.rb
Labels: team-captains, tech-review-ok

#116 [TECH] Documenter l'exécution en production
  .editorconfig
  docs/INSTALLATION.md
  sample.env
Labels: tech-review-needed, team-captains
